[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.package]
version = "0.0.0"
authors = ["Guillaume MICHEL <guillaume@orilla.fr>"]
description = "N-Body simulation"
edition = "2021"
license = "MIT License"

[workspace.dependencies]
num = "0.4.2"
rand = "0.8.5"

